max_len_seq: 4
# symbol: [1, -1, -1, 1]

sync_word: [1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0]
sync_word_fuzz: 3

noise:
  mu: -90
  sigma: 5.3322

signal: -85

correlation_std_threshold: 4

quantization: 0

source_sample_period: 20 ns
destination_sample_period: 1 us
transmission_period: 700 us

logging_output: no
