max_len_seq: 4
# symbol: [1, -1, -1, 1]

sync_word: [1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0]
sync_word_fuzz: 3

noise:
  mu: -90
  sigma: 5.3322

signal: -60

correlation_std_threshold: 4

quantization: 0

carrier_sensing:
  mu: 0 us
  sigma: 2 us

destination_sample_period: 1 us
on_off_period: 50 us
transmit_time: 45 us

logging_output: no
