max_len_seq: 4
# symbol: [1, -1, -1, 1]

# sync_word: [1, 1, 0, 0]
# sync_word_fuzz: 0

noise:
  mu: -90
  sigma: 5.3322

signal: -85

quantization: 0

# These options are ignored if samples are simulated
source_sample_period: 20 ns
destination_sample_period: 1 us

transmission_period: 700 us

logging_output: no
